### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by JoeElMasry0213** [A200K/IDA-Pro-SigMaker#1]
can you share sdk ?

**Comment by A200K** [comment]
I'm sorry, I'd like to include the SDK for convenience, however, it is only available to IDA customers. 
I don't want to get sued by Hexrays for leaking their files, and I don't want my repository taken down because of copyright infringement, that's why I can't share it.
If you do have a license, here is the official download link: https://hex-rays.com/products/ida/support/ida/idasdk_pro82.zip

If you look deep enough in the internet though, older leaked versions of the IDA SDK might work as well.
