### ISSUE TITLE
Support for searching for signatures

### ISSUE THREAD

**Issue by coconutbird** [A200K/IDA-Pro-SigMaker#5]
I would love if you could implement the pattern search functionality from the original sig maker.

**Comment by A200K** [comment]
I didn't implement this so far, because the "Binary Search" (Alt+B) feature of IDA already implements pattern scanning (with its own signature format), which is what I mostly use:
![g0RszWB](https://github.com/A200K/IDA-Pro-SigMaker/assets/7504530/4a4b2600-95a0-44fa-a095-131ed57f1a35)

I could add a signature searching option though as well. Is there a specific input format you need?

**Comment by A200K** [comment]
I added support for signature searching, give it a try if you want to see if this is what you had in mind.
