### ISSUE TITLE
[Request] Allow for custom opcodes/Python instruction linkage.

### ISSUE THREAD

**Issue by gir489returns** [A200K/IDA-Pro-SigMaker#9]
I have recently started hammering away at how the GTA V Script VM works, and there's very little information about it, as it's a custom product only for the RAGE engine, so the only information that exists about it is basically estimations based on reverse engineering, some debug strings that have been left behind in some releases of RDR2, GTA V and GTA IV, and some less than legal means (someone yoinked the source code during the Rockstar breach). 

Anyway! The YimMenu team mostly uses this plugin written by our anti-anti-cheat engineer, which can be found here: https://github.com/yubie-re/ysc-ida

This is a simple Python plugin that converts the opcodes into text. Not very sophisticated, but neither is the script VM. 

After it's finished decompiling the YSC file, IDA will look something like this:

![image](https://github.com/user-attachments/assets/b5c4d401-8e63-44d6-99e8-c83fb64fb591)

However, you'll notice the head of the function immediately calls a function. If I tell your plugin to generate a signature right now, it will just find whatever unique string of bytes it can that is unique to this block of code. Which is 2D 02 04 00 00 5D 0E A7 07, which translates to the ENTER and the CALL instruction. As you may have guessed, the 5D instruction is CALL, followed by a 3 byte mask (Rockstar is weird). Globals are also susceptible to changing (except Global_262144, that's the tunables global, and it's always at 262144 because Rockstar declared it to start at 0x40000 of the memory block).

Yeah, that's a lot of words. Is there we could instruct the plugin on custom assembly instructions? Like tell it this is a CALL instruction followed by X masks, etc?

**Comment by A200K** [comment]
Hey,
thank you for your detailed explaination!

You basically want proper wildcard functionality for custom instructions, did I get that right?
I believe adding some sort of custom instruction definition mechanic would be quite cumbersome on my end.

However, I looked at the python script you mentioned, and I see how it defines the custom instructions: https://github.com/yubie-re/ysc-ida/blob/main/ysc.py#L612

If you look at my plugin, as long as its not ARM code, it will try to check for a nonzero"offb" variable, defined for any operand in an instruction (in order to mark it as a wildcardable operand):
https://github.com/A200K/IDA-Pro-SigMaker/blob/main/IDA%20Pro%20SigMaker/Main.cpp#L54-L64
https://hex-rays.com/products/ida/support/idapython_docs/ida_ua.html#ida_ua.op_t

Now, if I am not totally mistaken, you should be able to easily extend your python script with all of the individual operand offsets, e.g:

(given that your custom "call" instruction has 1 byte operator at the beginning and 3 bytes operand after that)

> elif insn.itype == OP_CALL:
>   insn.Op1.type = o_mem
>   insn.Op1.dtype = dt_dword
>   insn.Op1.addr = (insn.get_next_dword()) & 0xFFFFFF
>   _insn.Op1.offb = 1_
>   insn.size = 4

Then, the signature plugin should work without any changes.

**Comment by gir489returns** [comment]
> Now, if I am not totally mistaken, you should be able to easily extend your python script with all of the individual operand offsets, e.g:
> 
> (given that your custom "call" instruction has 1 byte operator at the beginning and 3 bytes operand after that)
> 
> > elif insn.itype == OP_CALL:
> > insn.Op1.type = o_mem
> > insn.Op1.dtype = dt_dword
> > insn.Op1.addr = (insn.get_next_dword()) & 0xFFFFFF
> > _insn.Op1.offb = 1_
> > insn.size = 4
> 
> Then, the signature plugin should work without any changes.

`Signature for 7A68A: 2D 02 04 00 00 5D ? ? ? 61`

That worked! Thanks!
